#!/usr/bin/env bash
set -euo pipefail

MODEL="${1:-Qwen/Qwen2.5-Coder-7B-Instruct}"

# Hatcher stage 2: many urgent agents become replay-ready together.
#
# This uses the multi-session harness after all initial turns complete, then
# starts a shared short tool wait so urgent replay due times line up. The point
# is to test the cliff where E2E priority can no longer make every urgent
# replay first because they are all urgent at once.
export EXPERIMENT_KIND="${EXPERIMENT_KIND:-multi_session}"
export WORKLOAD_SOURCE="${WORKLOAD_SOURCE:-synthetic}"
export REPORT_LABEL="${REPORT_LABEL:-hatcher_e2e_urgent_burst_$(date +%Y%m%d_%H%M%S)}"
export PRESSURE_PROFILE="${PRESSURE_PROFILE:-custom}"
export UPDATE_LATEST="${UPDATE_LATEST:-1}"
export MAX_TIMELINE_GAPS="${MAX_TIMELINE_GAPS:-64}"

export MODES="${MODES:-no_prefetch e2e_priority_hints}"
export SESSION_COUNT="${SESSION_COUNT:-12}"
export SYNC_REPLAY_AFTER_INITIALS="${SYNC_REPLAY_AFTER_INITIALS:-1}"
export ARRIVAL_SHAPE="${ARRIVAL_SHAPE:-burst}"
export BURST_SIZE="${BURST_SIZE:-12}"
export ARRIVAL_GAP_MS="${ARRIVAL_GAP_MS:-0}"
export BURST_GAP_MS="${BURST_GAP_MS:-0}"
export TOOL_WAIT_LIST_MS="${TOOL_WAIT_LIST_MS:-25}"
export TOOL_WAIT_JITTER_MS="${TOOL_WAIT_JITTER_MS:-0}"

export BACKGROUND_FILLERS_PER_SESSION="${BACKGROUND_FILLERS_PER_SESSION:-0}"
export REQUEST_CONCURRENCY="${REQUEST_CONCURRENCY:-12}"
export FILLER_PROMPT_TOKENS="${FILLER_PROMPT_TOKENS:-1536}"
export TARGET_PROMPT_TOKENS="${TARGET_PROMPT_TOKENS:-4096}"
export SYNTHETIC_PROMPT_TOKENS="${SYNTHETIC_PROMPT_TOKENS:-4096}"
export SYNTHETIC_REPLAY_SUFFIX_TOKENS="${SYNTHETIC_REPLAY_SUFFIX_TOKENS:-256}"

export MAX_TOTAL_TOKENS="${MAX_TOTAL_TOKENS:-12288}"
export HICACHE_SIZE_GB="${HICACHE_SIZE_GB:-8}"
export MEM_FRACTION_STATIC="${MEM_FRACTION_STATIC:-0.72}"
export AGENTIC_KV_TRACE_SCHEDULER="${AGENTIC_KV_TRACE_SCHEDULER:-1}"
export AGENTIC_KV_TRACE_KV_POOL="${AGENTIC_KV_TRACE_KV_POOL:-1}"
export AGENTIC_RUNTIME_TELEMETRY="${AGENTIC_RUNTIME_TELEMETRY:-1}"
export AGENTIC_RUNTIME_TELEMETRY_BACKEND="${AGENTIC_RUNTIME_TELEMETRY_BACKEND:-sglang}"
export AGENTIC_KV_GPU_UTIL_SAMPLER="${AGENTIC_KV_GPU_UTIL_SAMPLER:-1}"
export GPU_UTIL_SAMPLE_INTERVAL_MS="${GPU_UTIL_SAMPLE_INTERVAL_MS:-100}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIRECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${DIRECT_ROOT}"

echo "Hatcher E2E Urgent Burst"
echo "MODEL=${MODEL}"
echo "REPORT_LABEL=${REPORT_LABEL}"
echo "MODES=${MODES}"
echo "SESSION_COUNT=${SESSION_COUNT}"
echo "SYNC_REPLAY_AFTER_INITIALS=${SYNC_REPLAY_AFTER_INITIALS}"
echo "TOOL_WAIT_LIST_MS=${TOOL_WAIT_LIST_MS}"
echo "TARGET_PROMPT_TOKENS=${TARGET_PROMPT_TOKENS}"
echo "BACKGROUND_FILLERS_PER_SESSION=${BACKGROUND_FILLERS_PER_SESSION}"
echo "REQUEST_CONCURRENCY=${REQUEST_CONCURRENCY}"
echo "AGENTIC_RUNTIME_TELEMETRY=${AGENTIC_RUNTIME_TELEMETRY}"
echo "AGENTIC_RUNTIME_TELEMETRY_BACKEND=${AGENTIC_RUNTIME_TELEMETRY_BACKEND}"

bash scripts/run_master_report.sh "${MODEL}"
