#!/usr/bin/env bash
set -euo pipefail

MODEL="${1:-Qwen/Qwen2.5-Coder-7B-Instruct}"
RESULT_ROOT="${RESULT_ROOT:-artifacts/results/milestone38_dynamo_hints_projection_$(date +%Y%m%d_%H%M%S)}"
LATEST_REPORT_ROOT="${LATEST_REPORT_ROOT:-artifacts/results}"
WORKLOAD_SOURCE="${WORKLOAD_SOURCE:-synthetic}"
MODES="${MODES:-no_prefetch dynamo_priority_hints}"
SESSION_COUNT="${SESSION_COUNT:-12}"
ARRIVAL_SHAPE="${ARRIVAL_SHAPE:-burst}"
ARRIVAL_GAP_MS="${ARRIVAL_GAP_MS:-40}"
BURST_SIZE="${BURST_SIZE:-4}"
BURST_GAP_MS="${BURST_GAP_MS:-400}"
TOOL_WAIT_LIST_MS="${TOOL_WAIT_LIST_MS:-250 500}"
PREFETCH_TIMING="${PREFETCH_TIMING:-early}"
HINT_DELAY_MS="${HINT_DELAY_MS:-10}"
PREFETCH_LEAD_MS="${PREFETCH_LEAD_MS:-120}"
PRIORITY_PREFETCH_WINDOW_MS="${PRIORITY_PREFETCH_WINDOW_MS:-750}"
PRIORITY_POST_PREFETCH_QUIET_MS="${PRIORITY_POST_PREFETCH_QUIET_MS:-750}"
DEADLINE_RESERVE_WINDOW_MS="${DEADLINE_RESERVE_WINDOW_MS:-500}"
BACKGROUND_FILLERS_PER_SESSION="${BACKGROUND_FILLERS_PER_SESSION:-4}"
FILLER_PROMPT_TOKENS="${FILLER_PROMPT_TOKENS:-1024}"
SYNTHETIC_PROMPT_TOKENS="${SYNTHETIC_PROMPT_TOKENS:-4096}"
SYNTHETIC_REPLAY_SUFFIX_TOKENS="${SYNTHETIC_REPLAY_SUFFIX_TOKENS:-256}"
REQUEST_CONCURRENCY="${REQUEST_CONCURRENCY:-8}"
MAX_TOTAL_TOKENS="${MAX_TOTAL_TOKENS:-12288}"
HICACHE_SIZE_GB="${HICACHE_SIZE_GB:-16}"
MEM_FRACTION_STATIC="${MEM_FRACTION_STATIC:-0.72}"
MAX_TIMELINE_GAPS="${MAX_TIMELINE_GAPS:-32}"

export RESULT_ROOT
export LATEST_REPORT_ROOT
export WORKLOAD_SOURCE
export MODES
export SESSION_COUNT
export ARRIVAL_SHAPE
export ARRIVAL_GAP_MS
export BURST_SIZE
export BURST_GAP_MS
export TOOL_WAIT_LIST_MS
export PREFETCH_TIMING
export HINT_DELAY_MS
export PREFETCH_LEAD_MS
export PRIORITY_PREFETCH_WINDOW_MS
export PRIORITY_POST_PREFETCH_QUIET_MS
export DEADLINE_RESERVE_WINDOW_MS
export BACKGROUND_FILLERS_PER_SESSION
export FILLER_PROMPT_TOKENS
export SYNTHETIC_PROMPT_TOKENS
export SYNTHETIC_REPLAY_SUFFIX_TOKENS
export REQUEST_CONCURRENCY
export MAX_TOTAL_TOKENS
export HICACHE_SIZE_GB
export MEM_FRACTION_STATIC
export MAX_TIMELINE_GAPS

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIRECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${DIRECT_ROOT}"

echo "Milestone 38: Dynamo Priority Hints vs Projected Hardware"
echo "This measures no_prefetch and dynamo_priority_hints. The report adds projected hardware rows from measured KV H2D durations."
echo "Projected hardware rows are estimates, not measured SGLang requests."

bash scripts/run_milestone36_multi_session_agentic_replay.sh "${MODEL}"
