#!/usr/bin/env bash
set -euo pipefail

MODEL="${1:-Qwen/Qwen2.5-Coder-7B-Instruct}"
RESULT_LABEL="${RESULT_LABEL:-priority_queue_sanity_v0511_$(date +%Y%m%d_%H%M%S)}"
RESULT_ROOT="${RESULT_ROOT:-artifacts/results/runs/controlled/${RESULT_LABEL}}"
LATEST_REPORT_ROOT="${LATEST_REPORT_ROOT:-artifacts/results/reports/${RESULT_LABEL}}"
SGLANG_DOCKER_IMAGE="${SGLANG_DOCKER_IMAGE:-local/dynamo-sglang:runtime-json-logs-ec2}"
SGLANG_DOCKER_PULL="${SGLANG_DOCKER_PULL:-0}"

export RESULT_ROOT
export LATEST_REPORT_ROOT
export SGLANG_DOCKER_IMAGE
export SGLANG_DOCKER_PULL

export WORKLOAD_SOURCE="${WORKLOAD_SOURCE:-synthetic}"
export MODES="${MODES:-dynamo_priority_hints}"
export MAX_PAIRS="${MAX_PAIRS:-1}"
export TOOL_WAIT_LIST_MS="${TOOL_WAIT_LIST_MS:-500}"
export FILLER_LIST="${FILLER_LIST:-48}"
export REQUEST_CONCURRENCY="${REQUEST_CONCURRENCY:-16}"
export FILLER_PROMPT_TOKENS="${FILLER_PROMPT_TOKENS:-1024}"
export TARGET_PROMPT_TOKENS="${TARGET_PROMPT_TOKENS:-3072}"
export SYNTHETIC_PROMPT_TOKENS="${SYNTHETIC_PROMPT_TOKENS:-3072}"
export SYNTHETIC_REPLAY_SUFFIX_TOKENS="${SYNTHETIC_REPLAY_SUFFIX_TOKENS:-128}"
export MAX_TOTAL_TOKENS="${MAX_TOTAL_TOKENS:-12288}"
export HICACHE_SIZE_GB="${HICACHE_SIZE_GB:-14}"
export MEM_FRACTION_STATIC="${MEM_FRACTION_STATIC:-0.72}"
export DYNAMO_HIGH_PRIORITY="${DYNAMO_HIGH_PRIORITY:-100}"
export DYNAMO_NORMAL_PRIORITY="${DYNAMO_NORMAL_PRIORITY:-0}"
export DYNAMO_LOW_PRIORITY="${DYNAMO_LOW_PRIORITY:--100}"
export DYNAMO_SCHEDULE_POLICY="${DYNAMO_SCHEDULE_POLICY:-fcfs}"
export DYNAMO_RADIX_EVICTION_POLICY="${DYNAMO_RADIX_EVICTION_POLICY:-priority}"
export AGENTIC_KV_TRACE_SCHEDULER="${AGENTIC_KV_TRACE_SCHEDULER:-1}"
export AGENTIC_KV_TRACE_KV_POOL="${AGENTIC_KV_TRACE_KV_POOL:-1}"
export MAX_TIMELINE_GAPS="${MAX_TIMELINE_GAPS:-8}"
export UPDATE_LATEST="${UPDATE_LATEST:-0}"

echo "Priority Queue Sanity"
echo "MODEL=${MODEL}"
echo "RESULT_ROOT=${RESULT_ROOT}"
echo "SGLANG_DOCKER_IMAGE=${SGLANG_DOCKER_IMAGE}"
echo "MODES=${MODES}"
echo "FILLER_LIST=${FILLER_LIST}"
echo "REQUEST_CONCURRENCY=${REQUEST_CONCURRENCY}"
echo "DYNAMO_SCHEDULE_POLICY=${DYNAMO_SCHEDULE_POLICY}"
echo "DYNAMO_RADIX_EVICTION_POLICY=${DYNAMO_RADIX_EVICTION_POLICY}"

bash scripts/run_milestone27_real_prompt_controlled_replay.sh "${MODEL}"

echo
echo "Priority queue audit:"
echo "  ${RESULT_ROOT}/controlled_replay_report/dynamo_priority_queue_effectiveness.csv"
echo "HTML report:"
echo "  ${RESULT_ROOT}/controlled_replay_report/controlled_replay_report.html"
