#!/usr/bin/env bash
set -euo pipefail

MODEL="${1:-Qwen/Qwen2.5-Coder-7B-Instruct}"

# Hatcher stage 1: the main cliff case.
#
# This keeps the experiment controlled and forensic: the same synthetic replay
# gaps are compared across baseline, Dynamo priority metadata only, and the
# end-to-end priority path.
export EXPERIMENT_KIND="${EXPERIMENT_KIND:-controlled}"
export WORKLOAD_SOURCE="${WORKLOAD_SOURCE:-synthetic}"
export REPORT_LABEL="${REPORT_LABEL:-hatcher_e2e_priority_cliff_$(date +%Y%m%d_%H%M%S)}"
export PRESSURE_PROFILE="${PRESSURE_PROFILE:-custom}"
export UPDATE_LATEST="${UPDATE_LATEST:-1}"
export MAX_TIMELINE_GAPS="${MAX_TIMELINE_GAPS:-48}"

export MODES="${MODES:-no_prefetch dynamo_priority_hints e2e_priority_hints}"
export MAX_PAIRS="${MAX_PAIRS:-6}"
export TOOL_WAIT_LIST_MS="${TOOL_WAIT_LIST_MS:-25 50 100}"
export FILLER_LIST="${FILLER_LIST:-32 64 128}"
export REQUEST_CONCURRENCY="${REQUEST_CONCURRENCY:-8}"
export FILLER_PROMPT_TOKENS="${FILLER_PROMPT_TOKENS:-1536}"
export TARGET_PROMPT_TOKENS="${TARGET_PROMPT_TOKENS:-4096}"
export SYNTHETIC_PROMPT_TOKENS="${SYNTHETIC_PROMPT_TOKENS:-4096}"
export SYNTHETIC_REPLAY_SUFFIX_TOKENS="${SYNTHETIC_REPLAY_SUFFIX_TOKENS:-256}"
export FILLER_DIVERGE_EARLY="${FILLER_DIVERGE_EARLY:-1}"

export MAX_TOTAL_TOKENS="${MAX_TOTAL_TOKENS:-12288}"
export HICACHE_SIZE_GB="${HICACHE_SIZE_GB:-8}"
export MEM_FRACTION_STATIC="${MEM_FRACTION_STATIC:-0.72}"
export AGENTIC_KV_TRACE_SCHEDULER="${AGENTIC_KV_TRACE_SCHEDULER:-1}"
export AGENTIC_KV_TRACE_KV_POOL="${AGENTIC_KV_TRACE_KV_POOL:-1}"
export AGENTIC_RUNTIME_TELEMETRY="${AGENTIC_RUNTIME_TELEMETRY:-1}"
export AGENTIC_RUNTIME_TELEMETRY_BACKEND="${AGENTIC_RUNTIME_TELEMETRY_BACKEND:-sglang}"
export AGENTIC_KV_GPU_UTIL_SAMPLER="${AGENTIC_KV_GPU_UTIL_SAMPLER:-1}"
export GPU_UTIL_SAMPLE_INTERVAL_MS="${GPU_UTIL_SAMPLE_INTERVAL_MS:-100}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIRECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${DIRECT_ROOT}"

echo "Hatcher E2E Priority Cliff"
echo "MODEL=${MODEL}"
echo "REPORT_LABEL=${REPORT_LABEL}"
echo "MODES=${MODES}"
echo "TOOL_WAIT_LIST_MS=${TOOL_WAIT_LIST_MS}"
echo "TARGET_PROMPT_TOKENS=${TARGET_PROMPT_TOKENS}"
echo "SYNTHETIC_PROMPT_TOKENS=${SYNTHETIC_PROMPT_TOKENS}"
echo "FILLER_LIST=${FILLER_LIST}"
echo "REQUEST_CONCURRENCY=${REQUEST_CONCURRENCY}"
echo "AGENTIC_RUNTIME_TELEMETRY=${AGENTIC_RUNTIME_TELEMETRY}"
echo "AGENTIC_RUNTIME_TELEMETRY_BACKEND=${AGENTIC_RUNTIME_TELEMETRY_BACKEND}"

bash scripts/run_master_report.sh "${MODEL}"
