#!/usr/bin/env bash
set -euo pipefail

MODEL="${1:-Qwen/Qwen2.5-Coder-7B-Instruct}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}/.."

if [[ -x ".venv/bin/python" ]]; then
  export PATH="${PWD}/.venv/bin:${PATH}"
  export PYTHON_BIN="${PYTHON_BIN:-.venv/bin/python}"
fi

export REPORT_LABEL="${REPORT_LABEL:-proactive_kv_management_deadline_kv_lane_$(date +%Y%m%d_%H%M%S)}"
export HARNESSES="${HARNESSES:-hatcher}"
export PRESSURE_LEVELS="${PRESSURE_LEVELS:-p3_high}"
export MODES="${MODES:-no_prefetch controller_proactive_kv_management}"

# Scenario 2 all-request pass:
# - 1 main session + 15 peer replay sessions = 16 sessions
# - 2 replay steps per session = 32 replay requests per mode
# - every replay session has its own prefix_id and cache-value signals
# - manager-facing analysis should treat every replay as a real request
export P3_HIGH_KNOBS="${P3_HIGH_KNOBS:-tool_wait_ms=1000 target_prompt_tokens=4096 filler_sessions=15 filler_prompt_tokens=4096 session_count=1 concurrency=6}"
export TASK_REPLAY_STEPS="${TASK_REPLAY_STEPS:-2}"
export FILLER_REPLAY_DEADLINES="${FILLER_REPLAY_DEADLINES:-1}"
export TOOL_WAIT_PROFILE="${TOOL_WAIT_PROFILE:-realistic_deadline_fair}"
export TOOL_WAIT_PROFILE_SPEC="${TOOL_WAIT_PROFILE_SPEC:-very_short:20:100-500,short:35:1000-5000,medium:30:10000-30000,long:15:60000-120000}"
export TOOL_WAIT_SEED="${TOOL_WAIT_SEED:-20260916}"
export WORKLOAD_SHAPE_MODE_INDEPENDENT="${WORKLOAD_SHAPE_MODE_INDEPENDENT:-1}"
export AGENTIC_WORKLOAD_PROFILE="${AGENTIC_WORKLOAD_PROFILE:-synthetic_pressure}"

export TRACE_PROFILE="${TRACE_PROFILE:-controller_decision}"
export TRACE_CONTROLLER_DECISIONS="${TRACE_CONTROLLER_DECISIONS:-1}"
export TRACE_CONTROLLER_COMPLETION_LINKAGE="${TRACE_CONTROLLER_COMPLETION_LINKAGE:-1}"
export AGENTIC_KV_TARGETED_PREFETCH_HOOK="${AGENTIC_KV_TARGETED_PREFETCH_HOOK:-1}"
export AGENTIC_KV_PREPARE_CONTROL_ENABLE="${AGENTIC_KV_PREPARE_CONTROL_ENABLE:-1}"
export AGENTIC_KV_PREPARE_CONTROL_HOST="${AGENTIC_KV_PREPARE_CONTROL_HOST:-127.0.0.1}"
export AGENTIC_KV_PREPARE_CONTROL_PORT="${AGENTIC_KV_PREPARE_CONTROL_PORT:-31991}"
export AGENTIC_KV_PREPARE_CONTROL_URL="${AGENTIC_KV_PREPARE_CONTROL_URL:-http://127.0.0.1:31991/prepare_prefix_kv}"
export AGENTIC_KV_PREPARE_WAIT_TIMEOUT_MS="${AGENTIC_KV_PREPARE_WAIT_TIMEOUT_MS:-5000}"
export CONTROLLER_DIRECT_LOAD_MECHANISM="${CONTROLLER_DIRECT_LOAD_MECHANISM:-prepared_prefix_control}"
export CONTROLLER_DIRECT_LOAD_FIXED_MS="${CONTROLLER_DIRECT_LOAD_FIXED_MS:-1000}"
export CONTROLLER_DIRECT_LOAD_MS_PER_TOKEN="${CONTROLLER_DIRECT_LOAD_MS_PER_TOKEN:-2.0}"
export CONTROLLER_DIRECT_LOAD_ESTIMATE_MULTIPLIER="${CONTROLLER_DIRECT_LOAD_ESTIMATE_MULTIPLIER:-3.0}"
export CONTROLLER_DIRECT_LOAD_SAFETY_MARGIN_MS="${CONTROLLER_DIRECT_LOAD_SAFETY_MARGIN_MS:-750}"
export CONTROLLER_DIRECT_LOAD_REQUIRE_COMPLETION="${CONTROLLER_DIRECT_LOAD_REQUIRE_COMPLETION:-1}"
export CONTROLLER_DIRECT_LOAD_ALLOWED_WAIT_CLASSES="${CONTROLLER_DIRECT_LOAD_ALLOWED_WAIT_CLASSES:-long}"
export CONTROLLER_DIRECT_LOAD_SELECTIVE_ADMISSION="${CONTROLLER_DIRECT_LOAD_SELECTIVE_ADMISSION:-1}"
export CONTROLLER_DIRECT_LOAD_MIN_SAVED_TOKENS="${CONTROLLER_DIRECT_LOAD_MIN_SAVED_TOKENS:-1024}"
export REPORT_BUILDER_MODE="${REPORT_BUILDER_MODE:-lightweight}"
export UPDATE_LATEST="${UPDATE_LATEST:-1}"

echo "Proactive KV management realistic run"
echo "REPORT_LABEL=${REPORT_LABEL}"
echo "MODES=${MODES}"
echo "TOOL_WAIT_PROFILE_SPEC=${TOOL_WAIT_PROFILE_SPEC}"
echo "TOOL_WAIT_SEED=${TOOL_WAIT_SEED}"
echo "WORKLOAD_SHAPE_MODE_INDEPENDENT=${WORKLOAD_SHAPE_MODE_INDEPENDENT}"
echo "AGENTIC_KV_TARGETED_PREFETCH_HOOK=${AGENTIC_KV_TARGETED_PREFETCH_HOOK}"
echo "AGENTIC_KV_PREPARE_CONTROL_ENABLE=${AGENTIC_KV_PREPARE_CONTROL_ENABLE}"
echo "AGENTIC_KV_PREPARE_CONTROL_URL=${AGENTIC_KV_PREPARE_CONTROL_URL}"
echo "CONTROLLER_DIRECT_LOAD_MECHANISM=${CONTROLLER_DIRECT_LOAD_MECHANISM}"
echo "CONTROLLER_DIRECT_LOAD_FIXED_MS=${CONTROLLER_DIRECT_LOAD_FIXED_MS}"
echo "CONTROLLER_DIRECT_LOAD_MS_PER_TOKEN=${CONTROLLER_DIRECT_LOAD_MS_PER_TOKEN}"
echo "CONTROLLER_DIRECT_LOAD_ESTIMATE_MULTIPLIER=${CONTROLLER_DIRECT_LOAD_ESTIMATE_MULTIPLIER}"
echo "CONTROLLER_DIRECT_LOAD_SAFETY_MARGIN_MS=${CONTROLLER_DIRECT_LOAD_SAFETY_MARGIN_MS}"
echo "CONTROLLER_DIRECT_LOAD_REQUIRE_COMPLETION=${CONTROLLER_DIRECT_LOAD_REQUIRE_COMPLETION}"
echo "CONTROLLER_DIRECT_LOAD_ALLOWED_WAIT_CLASSES=${CONTROLLER_DIRECT_LOAD_ALLOWED_WAIT_CLASSES}"
echo "CONTROLLER_DIRECT_LOAD_SELECTIVE_ADMISSION=${CONTROLLER_DIRECT_LOAD_SELECTIVE_ADMISSION}"
echo "CONTROLLER_DIRECT_LOAD_MIN_SAVED_TOKENS=${CONTROLLER_DIRECT_LOAD_MIN_SAVED_TOKENS}"
echo "DIRECT_KV_PREPARE_POLICY=prepared_prefix_control_ordered_by_replay_due_time"
echo "DIRECT_KV_SELECTIVE_ADMISSION=plan_only_then_load_only_host_resident_evicted_prefixes"

bash scripts/run_harness_deadline_pressure.sh "${MODEL}"
